//! Semantic-layer DTOs shared across the Profiler/IntentRag/ingestion path.
//!
//! These are the `semantic_catalog` row shape (built by the L0 Profiler at
//! onboarding, `specs/13 §2`) and the retrieval hit shape returned by the L1
//! IntentRag (`specs/13 §2`). Plain DTOs; validation happens at the boundary
//! (Profiler + ingress), not on these types.

use serde::{Deserialize, Serialize};

/// The semantic role of a catalogued column (drives classification + the agent's
/// DSL composition). Serialises `camelCase` to match the wire contract.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum SemanticType {
    /// A primary/subject identifier (e.g. `user_id`).
    Identifier,
    /// A categorical dimension (e.g. `country`).
    Dimension,
    /// An aggregatable numeric measure (e.g. `amount`).
    Measure,
    /// An event timestamp column (e.g. `created_at`).
    EventTs,
    /// Personally-identifiable information (redacted in samples; I4).
    Pii,
    /// A foreign key referencing another table's identifier.
    Fk,
    /// A table-level catalogue row (no column; the whole relation — issue #19).
    Table,
}

impl SemanticType {
    /// The wire label for this semantic type.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Identifier => "identifier",
            Self::Dimension => "dimension",
            Self::Measure => "measure",
            Self::EventTs => "eventTs",
            Self::Pii => "pii",
            Self::Fk => "fk",
            Self::Table => "table",
        }
    }

    /// Parse the wire label produced by [`Self::as_str`] back into a
    /// [`SemanticType`]. Returns `None` for any unknown label (defence-in-depth:
    /// the catalogue is read across a trust boundary, so an unknown value is
    /// rejected rather than coerced).
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "identifier" => Some(Self::Identifier),
            "dimension" => Some(Self::Dimension),
            "measure" => Some(Self::Measure),
            "eventTs" => Some(Self::EventTs),
            "pii" => Some(Self::Pii),
            "fk" => Some(Self::Fk),
            "table" => Some(Self::Table),
            _ => None,
        }
    }
}

/// One row of `semantic_catalog` (entity_type = `table` or `column`). Built by
/// the L0 Profiler and written via the single ingestion writer.
#[derive(Debug, Clone, PartialEq)]
pub struct CatalogRow {
    /// `table` for the table-level row, `column` for a column-level row.
    pub entity_type: String,
    /// Source system identifier.
    pub system: String,
    /// Source table (entity) identifier.
    pub table_name: String,
    /// Column name (`None` for the table-level row).
    pub column_name: Option<String>,
    /// Semantic role of the column.
    pub semantic_type: SemanticType,
    /// DuckDB logical type (e.g. `"VARCHAR"`, `"DOUBLE"`).
    pub data_type: String,
    /// Human-editable description (LLM-generated by default).
    pub description: String,
    /// Whether this column carries PII (samples redacted when true; I4).
    pub pii_flag: bool,
    /// Bounded sample values (≤20, each ≤`sample_value_bytes`; PII redacted).
    pub sample_values: serde_json::Value,
    /// Embedding of the description (NOT of PII values; I4).
    pub embedding: Vec<f32>,
    /// Epoch (secs) of the source state this catalogue entry was built from
    /// (spec 13 I5 / issue #18): the query path warns when a referenced
    /// column's entry is older than the source's latest ingest; a re-onboard
    /// appends a newer row (versioned delta) instead of overwriting.
    pub source_epoch: i64,
}

/// One retrieval hit from the L1 IntentRag: a candidate table/column with a
/// relevance score, returned to the agent so it can compose the DSL.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogHit {
    /// Source system identifier.
    pub system: String,
    /// Source table (entity) identifier.
    pub table_name: String,
    /// Column name (`None` for a table-level hit).
    pub column_name: Option<String>,
    /// Semantic role of the column.
    pub semantic_type: SemanticType,
    /// Human-editable description.
    pub description: String,
    /// Cosine-similarity score in `[0,1]` (higher = more relevant).
    pub score: f64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_round_trip_table_semantic_type_on_wire() {
        // Issue #19: `Table` must serialise to camelCase "table" and parse
        // back — the catalogue is read across a trust boundary, so an unknown
        // label is rejected, not coerced.
        let t = SemanticType::Table;
        let wire = serde_json::to_string(&t).expect("serialize");
        assert_eq!(wire, "\"table\"", "Table must serialize as camelCase table");
        let parsed: SemanticType = serde_json::from_str(&wire).expect("parse");
        assert_eq!(parsed, SemanticType::Table);
        assert_eq!(SemanticType::parse("table"), Some(SemanticType::Table));
        assert_eq!(
            SemanticType::parse("bogus"),
            None,
            "unknown labels rejected"
        );
        assert_eq!(SemanticType::Table.as_str(), "table");
    }
}
